name: what_is_a_hypothesis

channels:
- conda-forge
- defaults

dependencies:
- graphviz >=2.38,<3
- importnb  ==0.3.1
- ipywidgets >=7.2,<7.3
- joblib >=0.11,<0.12
- jupyterlab >=0.32,<0.33
- nodejs >=8,<9
- notebook >=5.5,<5.6
- pandas >=0.23,<0.24
- pip <10
- pytest >=3.6,<3.7
- python-graphviz >=0.8,<0.9
- requests >=2.18,<2.19
- toolz >=0.9, <0.10
- pip:
  - poser ==0.1.2
