name: what_is_a_hypothesis

channels:
- conda-forge
- defaults

dependencies:
- graphviz >2.38,<3
- importnb  ==0.3.1
- ipywidgets >=7.2.1,<7.3
- jupyterlab >=0.32,<0.33
- nodejs >8,<9
- pandas >=0.23,<0.24
- pip <10
- python-graphviz >=0.8.3,<0.9
- pytest >=3.6.1,<3.7
- pip:
  - poser ==0.1.2
